package weverse

var AccountDefaultHeaders = map[string]string{
	"Host": "accountapi.weverse.io",
	"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0",
	"Accept": "*/*",
	"Accept-Language": "en-US,en;q=0.7,ko-KR;q=0.3",
	"Accept-Encoding": "gzip, deflate, br, zstd",
	"Content-Type": "application/json",
	"Referer": "https://account.weverse.io/",
	"x-acc-app-secret": "5419526f1c624b38b10787e5c10b2a7a",
	"x-acc-app-version": "3.0.0",
	"x-acc-language": "en",
	"x-acc-service-id": "weverse",
	"x-acc-trace-id": "1",
	"x-clog-user-device-id": "1",
	"Origin": "https://account.weverse.io",
	"DNT": "1",
	"Sec-GPC": "1",
	"Connection": "keep-alive",
	"Sec-Fetch-Dest": "empty",
	"Sec-Fetch-Mode": "cors",
	"Sec-Fetch-Site": "same-site",
	"Priority": "u=0",
	"Pragma": "no-cache",
	"Cache-Control": "no-cache",
	"TE": "trailers",
}

var SDKDefaultHeaders = map[string]string{
	"Host": "sdk.weverse.io",
	"Accept": "*/*",
	"X-SDK-SERVICE-ID": "weverse",
	"X-SDK-LANGUAGE": "ko",
	"X-CLOG-USER-DEVICE-ID": "1",
	"X-SDK-PLATFORM": "iOS",
	"Accept-Language": "ko-KR,ko;q=0.9",
	"Accept-Encoding": "gzip, deflate, br",
	"Content-Type": "application/json",
	"X-SDK-VERSION": "3.7.0",
	"User-Agent": "Weverse/3.6.0.30 CFNetwork/3826.500.131 Darwin/24.5.0",
	"Connection": "keep-alive",
	"X-SDK-TRACE-ID": "1",
	"X-SDK-APP-VERSION": "2.2.1",
	"Pragma": "no-cache",
	"Cache-Control": "no-cache",
	"X-SDK-SERVICE-SECRET": "9d79660be5ca452ab8c93bcaee310bb7",
}

var WeverseDefaultHeaders = map[string]string{
	"Host": "weverse.io",
	"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0",
	"Accept": "application/json, text/plain, */*",
	"Accept-Language": "en-US,en;q=0.7,ko-KR;q=0.3",
	"Accept-Encoding": "gzip, deflate, br, zstd",
	"WEV-device-Id": "1",
	"WEV-wdm-v2": "off",
	"WEV-open-community": "A",
	"WEV-timezone-id": "Asia/Seoul",
	"Origin": "https://weverse.io",
	"DNT": "1",
	"Sec-GPC": "1",
	"Connection": "keep-alive",
	"Referer": "https://weverse.io/",
	"Sec-Fetch-Dest": "empty",
	"Sec-Fetch-Mode": "cors",
	"Sec-Fetch-Site": "cross-site",
	"Pragma": "no-cache",
	"Cache-Control": "no-cache",
	"TE": "trailers",
}

const HMACKey = "1b9cb6378d959b45714bec49971ade22e6e24e42"
const weverseBaseURL = "https://global.apis.naver.com/weverse/wevweb"